version: "3.1"
services:

  hivemetastore:
    image: postgres:11.5
    hostname: hivemetastore
    container_name: hivemetastore
    environment:
      POSTGRES_PASSWORD: new_password
    expose:
      - 5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      options:
          max-size : "200m"
    networks:
      capri_spark_net:
        ipv4_address: 172.28.1.4
    extra_hosts:
      - "livy:172.28.1.6"

  draco:
    image: ging/fiware-draco:FIWARE_7.8.1
    container_name: draco
    environment:
      - NIFI_WEB_HTTP_PORT=9090
    expose:
      - 1-65535
    ports:
      - "9090:9090"
      # Receiver port for Orion CB???
      - "5050:5050"
      - "5005:5005"
    volumes:
      - ./data/draco/hadoop_conf:/opt/nifi/nifi-current/hadoop_conf
      - ./data/draco/conf:/opt/nifi/nifi-current/conf
    extra_hosts:
      - "master:172.28.1.1"
    logging:
      options:
          max-size : "200m"
    networks:
      capri_spark_net:
        ipv4_address: 172.28.1.7
		
		
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'knowage'
      MYSQL_USER: 'knowage'
      MYSQL_PASSWORD: 'knowage'
      MYSQL_ROOT_PASSWORD: 'knowage'
    ports:
      - '3306:3306'
    expose:
      - '3306'
	logging:
      options:
          max-size : "200m"
    volumes:
      - db:/var/lib/mysql
    networks:
      capri_spark_net:
        ipv4_address: 172.28.1.8
  
  phpmyadmin:
    image: phpmyadmin
	restart: always
	ports:
	  - 8080:80
	environment:
	  -PMA_ARBITRARY=1
	logging:
      options:
          max-size : "200m"
	networks:
      capri_spark_net:
        ipv4_address: 172.28.1.9
		
  iot-agent:
    image: fiware/iotagent-ul
    hostname: iot-agent
    container_name: fiware-iot-agent
    depends_on:
      - iotmongo
    expose:
      - "4061"
      - "7896"
    ports:
      - "4061:4061"
      - "7896:7896"
    environment:
      - "IOTA_CB_HOST=orion"
	  - "IOTA_CB_PORT=1026"
	  - "IOTA_NORTH_PORT=4061"
	  - "IOTA_REGISTRY_TYPE=mongodb"
	  - "IOTA_MONGO_HOST=iot_mongo"
	  - "IOTA_MONGO_PORT=27017"
	  - "IOTA_MONGO_DB=iotagent-ul"
	  - "IOTA_HTTP_PORT=7896"
	  - "IOTA_PROVIDER_URL=http://iot-agent:4061"
	logging:
      options:
          max-size : "200m"
	networks:
      capri_spark_net:
        ipv4_address: 172.28.3.1
	
		
		
  iotmongo:
    hostname: iot_mongo
    image: mongo:4.2
    networks:
      - iotnet
	  - capri_spark_net
    volumes:
      - iot_mongo_data:/data/db
      - iot_mongo_conf:/data/configdb
    logging:
      options:
          max-size : "200m"
    networks:
      capri_spark_net:
        ipv4_address: 172.28.3.3

  orion:
    hostname: orion
    image: fiware/orion:latest
    networks:
      - hostnet
      - ocbnet
      - capri_spark_net
    ports:
      - "1026:1026"
      - "5000:5000"
    depends_on:
      - orion_mongo
      - quantumleap
    logging:
      options:
          max-size : "200m"
    # add -forwarding if using NGSI-ld
    #command: -statCounters -dbhost orion_mongo -logLevel INFO -forwarding
    command: -statCounters -dbhost orion_mongo -logLevel INFO -corsOrigin __ALL
    extra_hosts:
      - "draco:172.28.1.7"
    networks:
      capri_spark_net:
        ipv4_address: 172.28.3.10


 
networks:
  capri_spark_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16


volumes:
  spark_bin:
  iot_mongo_data:
  iot_mongo_conf:
  orion_mongo_data:
  orion_mongo_conf:
  db: